### ISSUE TITLE
session key not generated in src.env 

### ISSUE THREAD

**Issue by sbishop61** [rst0git/LegalRuleML-app#3]
I have followed the installation instructions but get an error on
`docker-compose exec web bash -c "php artisan `key:generate"``
> file_get_contents(/var/www/html/.env): failed to open stream: No such file or 

When I look in src.env the key has not been filled in.

When I try to access the container with a browser what is displayed is:

> Whoops, looks like something went wrong.

I think that is because there is no key for Laravel .

If that is the problem, how do I generate the key into src.env?

**Comment by rst0git** [comment]
Thank you for opening this issue. The build scripts and instructions have been updated.
